### ISSUE TITLE
蔡博士您好：有些发生器的问题向您求助

### ISSUE THREAD

**Issue by zawudui** [cai525/rigol-oscilloscope-and-generator#1]
蔡博士您好：
我的问题是这样。我目前想要使用matlab生成一个短暂的方波（如20KHz持续1ms 的方波），并暂停几ms到几十ms，如此作为一个周期，反复输出，通过matlab调整强度等参数。
因为我对这方面不太熟悉，目前还没有找到可行的方案。我尝试了一些其他人的生成任意波并输出的脚本，但最终显示在示波器上都失败了。如果您方便的话，可否留一个联系方式？
或者我的微信为：17681807450，邮箱为：1163167141@qq.com，您方便的话也可以加我。
有偿咨询，麻烦您了，谢谢~

**Comment by cai525** [comment]
因为我目前很久没有接触matlab以及硬件相关的内容，对该项目的问题比较生疏。通过matlab控制信号发生器，首先需要在matlab中安装硬件支持包。安装之后，只需要按照信号发生器编程指导文档的说明，向信号发生器发生特定指令，即可对信号发射器进行控制。网上有不少相关的内容可供参考，例如 [该篇文章](https://zhuanlan.zhihu.com/p/520066272) . 由于不同设备对应的指令集可能不同，所以需要参考设备文档中的编程指导相关部分，但核心还是利用matlab和设备间进行相关通信。祝调试顺利。

**Comment by zawudui** [comment]
谢谢您~目前我用burst模式达到了我的目的，虽然任意波模式尚未调试成功，但目前不用为这个烦恼了，非常感谢。
如果未来还有进一步的问题再向您请教。

祝身体健康，万事如意
Li JingWei

发件人: cai525 ***@***.***>
日期: 星期五, 2024年3月29日 00:07
收件人: cai525/rigol-oscilloscope-and-generator ***@***.***>
抄送: zawudui ***@***.***>, Author ***@***.***>
主题: Re: [cai525/rigol-oscilloscope-and-generator] 蔡博士您好：有些发生器的问题向您求助 (Issue #1)

因为我目前很久没有接触matlab以及硬件相关的内容，对该项目的问题比较生疏。通过matlab控制信号发生器，首先需要在matlab中安装硬件支持包。安装之后，只需要按照信号发生器编程指导文档的说明，向信号发生器发生特定指令，即可对信号发射器进行控制。网上有不少相关的内容可供参考，例如 该篇文章<https://zhuanlan.zhihu.com/p/520066272> . 由于不同设备对应的指令集可能不同，所以需要参考设备文档中的编程指导相关部分，但核心还是利用matlab和设备间进行相关通信。祝调试顺利。

―
